export { Home } from './home'
export { Shop } from './shop'
export { About } from './about'
export { ContactUs } from './contactUs'
export { Auth } from './auth'
export { ProductPage } from './productPage'
